
name: "My first Action (Basic-Schulung)"
description: "Greet someone"
author: "alexander.nurzhanov@md.de"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Stranger"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
